### ISSUE TITLE
Empty tags in Dark Utilities recipes, and other EMI issues

### ISSUE THREAD

**Issue by HLRxxKarl** [AllTheMods/ATM-9#10]
It seems EMI doesn't like it when a library mod decides to take over a vanilla recipe.
![2023-06-18_23 19 49](https://github.com/AllTheMods/ATM-9/assets/80851619/7ca64fc9-1a99-4dc8-a53b-7c9dc45ba16c)

But it works with Forge's crops tag and other blocks from mods. 
![2023-06-18_23 28 15](https://github.com/AllTheMods/ATM-9/assets/80851619/4597f0f5-3f1e-45eb-bec3-97e821feed20)

But if you try viewing a recipe tree that includes blocks from a mod, even if their recipes only use vanilla blocks, the recipe is not included in the tree. This is unfortunate, because this kind of defeats the whole purpose of this mod that would've made it useful. But it seems this has been regular behavior for this mod for some time, so nothing to do about that half. 
![2023-06-18_23 08 01](https://github.com/AllTheMods/ATM-9/assets/80851619/f5d33323-3b67-42df-ada5-fa41db964d94)

**Comment by emilyploszaj** [comment]
Hi! I'm the author of EMI so I just wanted to drop some things here. First, that barrier empty tag thing does not come from EMI. I believe it comes from JEI on the server, but it also may come from Forge. Either way, that recipe's ingredient is missing tags on a level before EMI or JEI even get to acknowledge it.

On the point about the recipe tree, that default functionality expands recipes that mods have specified you'll want expanded, but for mods that don't have this integration it'll leave nodes unexpanded. This isn't a problem, however, the user is able to click on any recipe and assign it themselves. They can also change or remove recipes the same way. It is basically impossible to always break down a recipe tree exactly as much as a user wants from the get go, so the tree is designed so that users can easily change it themselves by setting defaults or expanding the nodes when they need them. You can also try to "assume" a recipe by shift clicking an item in the tree.

If that was unclear, this is a video of it in action.

https://github.com/AllTheMods/ATM-9/assets/14813658/3efdce93-e766-42d5-9250-4b83f122f848
