### ISSUE TITLE
No nat gen Andesite/Diorite/Granite

### ISSUE THREAD

**Issue by ZombifiedRob** [AllTheMods/ATM-9#1001]
Caved and strip mined for many hours over multiple days without encountering a single natural deposit of andesite, diorite, or granite. Unsure which ore gen or biome mod is removing them.

The only exception is surface generation by several Biomes o Plenty biomes. Savanna has surface granite, Crag has surface andesite. The only way I have found to acquire diorite is to craft it.

**Comment by Schrimpes** [comment]
World generation is a bit strange at the moment anyway. I've walked around for hours in a newly created world and only found 2 villages. I haven't come across a dungeon from the mod "dungeon crawler" at all, but there are now these dust/sand piles from gregtech lying around everywhere, which don't have any correct text in jade, or are floating in the air. Not to mention the ore generation, since there are now so many mods in the pack that generate their own ore.

**Comment by tbureck** [comment]
I can confirm this is still an issue in v0.2.37.

**Comment by Kevin-Marsh** [comment]
Terralith changes the terrain generation extensively. You can use a nature's compass to located andesite, diorite, and granite caves.
