### ISSUE TITLE
Power issue with refined storage

### ISSUE THREAD

**Issue by chyper111** [AllTheMods/ATM-9#1019]
So I noticed if you connected more than 16000fe to the refined storage network this will cause it to blink off and on and not work. There's a posted issue in the refined storage Git Hub that says "This is caused by the mods adding a faster tick rate. they marked it as resolved and left it at that." 

The modpack I'm playing is ATM 9 Version 0.2.31.

Link to the GitHub page that talks about this issue.
https://github.com/refinedmods/refinedstorage/issues/3565

**Comment by XxNukeclearxX** [comment]
I'm actually having this same issue on All the Mods 9 version 0.2.34. For some odd reasoning, even when the configuration file is modified, it gets reverted back or even overwritten to its original value. I have also discovered this matter from another post from All the Mods 7: https://github.com/AllTheMods/ATM-7/issues/1393 

This issue however was labeled "won't fix." While yes, the argument of memory management can be applied, the secondary argument of where is the other 16k RF suddenly going then?

Please let me know if this issue becomes fixed or if a solution/workaround is discovered.

Thanks!

**Comment by XxNukeclearxX** [comment]
Hi again!

I was able to actually find a fix that was suggested from the ATM 7 link originally. If you follow the same order of modifying the RF limit, then you can possibly work around this.

Here's how to do it:
1. Locate your server files.
2. Locate the world file.
3. Locate the serverconfig file located inside of the world file.
4. Locate the file that is named refinedstorage -server.toml
5. Locate the part that mentions "[controller]" and then look for the part that says "capacity = 32000"

From there, you can modify it to become higher or lower. This is the only work around I have found, but in order to get it to apply you must shut down the server fully and THEN modify the file. After you're finished, it should work properly and the change should be applied.

Hope this helps!
