### ISSUE TITLE
Chemlib / Alchemistry Non-Functioning 

### ISSUE THREAD

**Issue by Purple0** [AllTheMods/ATM-9#1035]
issue with Alchemistry and Chemlib not functioning together making it impossible to make certain materials in the modpack to progress, such as Titanium from both Chemlib and Gregtech. 
Specific devices that are unable to be used are the Compactor from Alchemistry, putting materials inside of it (With power, and selecting a recipe) causes nothing to happen. 
![image](https://github.com/AllTheMods/ATM-9/assets/17939751/9f8539a6-600c-45f2-b383-2c38f178a1fd)

**Comment by aAndrew3030** [comment]
Some of the recipes are disabled to prevent cheesing Gregtech. This can be changed in kubejs > server_scripts > mods > chemlib > craftRemove.js

**Comment by screret** [comment]
make your damn titanium the intended way

**Comment by Purple0** [comment]
> make your damn titanium the intended way

And what exactly is the intended way? Because JEI doesn't list proper ways to craft it. Also don't be a dick about it buddy.

**Comment by Purple0** [comment]
> > make your damn titanium the intended way
> 
> And what exactly is the intended way? Because JEI doesn't list proper ways to craft it. Also don't be a dick about it buddy.

Also, i was trying to make ChemLib Titanium specifically, which you can see in the image above isn't working. And if it's intended for you to outright change the config just to make a mod work, then that is a fucking issue. Because this isn't a singleplayer world i'm playing on, it's a hosted server that isn't mine.

**Comment by aAndrew3030** [comment]
While the quests in this pack are optional, they do guide you in the process of making titanium the way the pack designers intended it to be made. If you don't want to play the pack the way it was designed, your only option is to modify it by changing the script I pointed to above. I have nothing to do with the development of this pack, but IMHO if this "issue" makes you mad, maybe you might try playing a different pack, or better yet, maybe go touch some grass. This is just a silly block game...

**Comment by Purple0** [comment]
> While the quests in this pack are optional, they do guide you in the process of making titanium the way the pack designers intended it to be made. If you don't want to play the pack the way it was designed, your only option is to modify it by changing the script I pointed to above. I have nothing to do with the development of this pack, but IMHO if these "issues" makes you mad, maybe you might try playing a different pack, or better yet, maybe go touch some grass. This is just a silly block game, nothing to get worked up about!

I wouldn't be getting worked up about it if there were more clear/accessible ways to access information regarding these mods, while the quest menu does exist, yes, trying to locate it and find said information is a hassle for someone new to one of these packs. And again as i've said before, i can't change anything regarding the configs or scripts since this is a >Hosted Server that isn't mine. And responses i get from users like screret just makes me assume everyone is gatekeeping information about this mod.

**Comment by alfredggttv** [comment]
I apologize for the earlier response on the intended way to make Titanium. That response was a little unwarranted.

IIRC, the alchem recipe was removed because of balance, making it easy to cheese the GT progression. However, Titanium didn't have any uses outside of GT, which is why it was removed. I believe the only way to make it is using GT, and I personally have no clue how to do GT myself. I don't make the questlines for it, but there is a questline that should take you all the way to Titanium if you need it.

As for gatekeeping, I personally get that as well. I feel like modded as a whole is incredibly difficult because a lot of the "fun" is hidden behind having the knowledge to do everything. JEI has also been a hassle, especially for something as complex as GT. I wouldn't worry about changing the configs, but definitely look into doing the GT questlines if you want to make it. Sorry for the confusion!
