### ISSUE TITLE
Vanilla Recipes Not Working.... 

### ISSUE THREAD

**Issue by Usamamqsood** [AllTheMods/ATM-9#1064]
It's been a month since I downloaded ATM9 multiple times. Everything downloads and installs perfectly, and it runs well. However, I'm having issues crafting ingots from nuggets, turning coal into coal blocks, and converting iron ingots into iron blocks. Additionally, I can't make glass by smelting sand. Please help if anyone knows how to fix these issues. Thank you.

**Comment by Kjelli** [comment]
I am also experiencing this on my self-hosted multiplayer server.

**Comment by Usamamqsood** [comment]
Im looking for a solution for a long time please let me know if you find out

**Comment by Kevin-Marsh** [comment]
This is caused by a corrupted install that doesn't register with the correct gregtech config file. Reinstalling and ensuring that the correct config is applied should fix it for anyone that finds this issue. This also applies for servers. The server owner should reinstall/update the server if you join a server and can't use these recipes.
