### ISSUE TITLE
Using the Structure Compass for non-available Vanilla structures crashes the game

### ISSUE THREAD

**Issue by SojaIntegral** [AllTheMods/ATM-9#1243]
I just crashed a server by accident by clicking on Minecraft:Desert_Pyramid on the Structure Compass.

The only extra mod the server had was Botany Pots Tiers.

**Comment by XxNukeclearxX** [comment]
I've had this error with two other structures on top of it. I've come to find out it's due to a mod conflict. 

The mod conflict would be the mod known as "YUNG's Better Dungeons, Nether Fortresses, End Island, Jungle Temples, Ocean Monuments, Mineshafts, Witch Huts, Strongholds, and Desert Temples" which all seem to be separate mods, but of course come into play with one another. Each one has "YUNG's" in front of them. I've come to discover that the Structure Compass freaks out when you look for the vanilla variant of these things but it does not seem to do so with the "better structure" versions of them. 

I hope this at least brings some clarity over it all!

**Comment by Kevin-Marsh** [comment]
We removed the ability to search for the effected structures. Please let us know if any more pop up in the future.
