### ISSUE TITLE
Rossinite not filling into Reprocessor

### ISSUE THREAD

**Issue by TheMalefic666** [AllTheMods/ATM-9#1355]
I've been working my way through extreme reactors, I've finally made Rossinite and I've tried filling up a preprocessor. The Meka pipe is full rossinite, but the reprocessor is not filling up at all. I've done the same method with all of my extreme reactor multiblock machines. I've tested different pipes and different tanks. The reprocessor does not seem to take the fluid at all. Yes, its set up to output and autoeject is on.
![2024-02-12_11 13 41](https://github.com/AllTheMods/ATM-9/assets/160072497/bef4fe5f-3a47-43b6-8136-665cea8fe9be)

**Comment by forsakendaemon** [comment]
I've had this happen too - the issue was that the wrong Rossinite was going in (the reactant rather than the regular fluid). I fixed it by setting up modular routers to bucket out of a Mekanism tank and into a dark tank (only the regular fluid appears in a bucket so it autoconverts once it's in a bucket), which I could then pull out of with the pipes.

**Comment by TheMalefic666** [comment]
> I've had this happen too - the issue was that the wrong Rossinite was going in (the reactant rather than the regular fluid). I fixed it by setting up modular routers to bucket out of a Mekanism tank and into a dark tank (only the regular fluid appears in a bucket so it autoconverts once it's in a bucket), which I could then pull out of with the pipes.

I have the regular fluid in there. I guess I'm confused lol

**Comment by TheMalefic666** [comment]
So it has to be the rossinite from the buckets... This is dumb lol
