### ISSUE TITLE
Tungstate and scheelite not spawning in end islands.

### ISSUE THREAD

**Issue by weeaudi** [AllTheMods/ATM-9#1453]
I can't find any tungstate or scheelite in the end islands anywhere no matter how much I look. The only place i can find it is the main island. is this intended? or is this a bug?

**Comment by weeaudi** [comment]
Version 51

**Comment by Rekalty** [comment]
GregTech ores were move to the mining dimension a couple of versions ago, have you tried looking there?

**Comment by weeaudi** [comment]
I am looking currently but still cant find it. is it super rare?

**Comment by weeaudi** [comment]
I have not found any tungstate, scheelite, or lithium in the mining dimension

**Comment by Mrminesheeps** [comment]
Would also like to add that a newly generated mining dimension is currently lacking scheelite veins, I have not checked for other types.

**Comment by weeaudi** [comment]
yeah thats the main problem im having

**Comment by loving2** [comment]
Thanks for raising this to our attention! It turns out that Scheelite, Beryllium, Manganese, Garnet, and Lapis were all affected by a mismatch of Y levels between the Mining Dimension layers and where the ores were trying to be placed. 

I linked a PR that has a fix in to address this, so hopefully in the next update we should have all of those veins and their ores generating properly in the Mining Dimension!

**Comment by weeaudi** [comment]
Thank you so much!
