### ISSUE TITLE
[Quests issues]: Exploration Ad Astra is titled "Blood Magic"

### ISSUE THREAD

**Issue by AlienXAXS** [AllTheMods/ATM-9#1515]
### Modpack Version

0.2.53

### Describe the issue

![image](https://github.com/AllTheMods/ATM-9/assets/1773445/5b070086-71b2-4253-b140-27dbc05c3b32)

A small typo I noticed here, for whatever reason in the Quests side-bar the Ad Astra section is titled "Blood Magic".  The icon is correct though :)

However, it looks like perhaps Blood Magic doesnt exist at all in the Magic section above?

**Comment by Mitchell5200** [comment]
![2024-03-19_19 07 02](https://github.com/AllTheMods/ATM-9/assets/45913837/083fa3cc-3177-4560-a881-5460959a0933)
Here's what the magic and Exploration section is meant to look like, my guess is that your launcher/server did not update the FTB quests files correctly in the configs folder, as the name changes are due to the translation key names in the `en_us.json` file we have made, for translation purposes.

**Comment by AlienXAXS** [comment]
Ah yes, thank you. Looking at the upload logs it seems there was some issues with the ./config folder.  All sorted!
