### ISSUE TITLE
PneumaticCraft Liquid Compressors won't run on PneumaticCraft fuels

### ISSUE THREAD

**Issue by Sarrdonous** [AllTheMods/ATM-9#155]
I am seeing this issue on version 0.0.45.
https://imgur.com/a/gnqK2eX

Newly crafted Liquid Compressors, including Advanced, will not accept PneumaticCraft fuels. I've verified this with Gasoline, LPG, and Crude Oil.
Also, my previously crafted compressors that are already loaded with Gasoline will not start.

I have verified that the compressors will accept other fuels, such as Lava and GregTech Steam.

**Comment by Sudoasroot** [comment]
i just tested - i can replicate the issue

**Comment by Bit-Flare** [comment]
Having the same issues. Running 0.0.45 as a server. Other fluids work (tested lava, steam, neutronium, and molten plastic), but all the pneumaticraft fuels don't.

However, the pneumaticraft fuels do work in a singleplayer world.

**Comment by CmdrFluffy** [comment]
Can confirm again, when on a server, the Pneumatic Craft Fuels, will not pump using pipez, nor will it power the compressors

**Comment by CmdrFluffy** [comment]
I think its GregTech that causes it to stop working, but that is just a guess at this time

**Comment by AENykorak** [comment]
Another confirmation of Pneumatic Craft Fuels not working, up to v0.0.50 of ATM9.
Have tested adjusting the config temp to no avail (as lava was working).
The Advanced Liquid Compressor will accept lava (both bucket and piped), but not Gasoline, Diesel, or Kerosene (piped or bucket).
I also suspect it is an incompatibility with GregTech, as I have enabled the uncrafting station and GregTech has many conflicts with other recipes, as evident by returned items and items being unusable when recieved from the uncrafting station (as if they have IDs but arent used in any recipes). I'm guessing because they were turned off by the ATM9 crew to make crafting more difficult and "end-game."
This issue is consistent since 0.46.

**Comment by AntiAlles** [comment]
v0.0.0.54 still the same issue 
Singleplayer works after some trickery but no chance for multiplayer

**Comment by desht** [comment]
PneumaticCraft author here.

Would appreciate any updates from the ATM9 pack devs on this problem, since there's a pretty regular stream of ATM9 (and no other pack) players turning up at the PNC discord wondering why their compressors are broken.

**Comment by AENykorak** [comment]
Hey everyone, update on my end.
With the newest update suggesting to start a new world we did just that and found out the fuel actually works.
We used gasoline in the compressor in the new world with no issues, but when I ported our old world to the new build it did not work. It seems to be an ID conflict some time around 0.0.45 that if you had an old compressor (or possibly old fuel) it wouldnt work.
You could test building a new machine and getting new fuel (as I did not try that), but the other option is to start a new world.
Hope this helps.

**Comment by FarzyYT** [comment]
> v0.0.0.54 still the same issue Singleplayer works after some trickery but no chance for multiplayer

I can't play multiplayer with friend we have error index 0 out of bounds for length 0
