### ISSUE TITLE
[Bug]: [GTCEu] Completing the micro universe orb causes async thread logic error

### ISSUE THREAD

**Issue by eziur** [AllTheMods/ATM-9#1618]
### Possible Fixes

Yes

### Modpack Version

0.2.56

### What happened?

I attempted multiple times to complete the micro universe orb multiblock with different methods, including autobuilding the entire structure with the terminal, autobuilding most of it but placing the last few blocks by hand, and finally building the entire multiblock by hand. Upon placing the final block that would normally cause the multiblock to form, the game drops to 0 tps and blocks stop dropping things, can't interact with anything, etc. The game cannot be closed, kill instance through ftb app does not work, the only way to exit is through task manager kill. On the most recent attempt, the final block placement caused a windows bluescreen error.

### latest.log

https://gist.github.com/eziur/043a4895ed938137536f9f2998d33fcd

**Comment by screret** [comment]
your log isn't complete.

**Comment by forsakendaemon** [comment]
I'm having the same issue - there's a full crash log here: [crash-2024-04-15_00.30.18-server.txt](https://github.com/AllTheMods/ATM-9/files/14972749/crash-2024-04-15_00.30.18-server.txt)

I tried upping the tick duration limit (from 120s to 1200s) to see whether it's just that checking the multi block is chugging, which seemed to work, although that could also be because I was leaving quite a while between individual block placements.

**Comment by cjx2154148** [comment]
My version is 0.2.60, also has the same bug. How did you solve it?

**Comment by 0xAdachi** [comment]
can someone please fix this already, why would you add a cool multiblock only for it to crash the world if you make it

**Comment by loving2** [comment]
I cannot recreate this issue on a fresh installation of ATM9 v0.3.5
