### ISSUE TITLE
[Bug]: GregTech Apiary MK2 does not funtion

### ISSUE THREAD

**Issue by SethaWetha** [AllTheMods/ATM-9#1649]
### Possible Fixes

Yes

### Modpack Version

0.2.57

### What happened?

When following the recipes provided in JEI, the Apiary MK2 does not do anything. I have tested the recipes with 1 through 5 Sulfur Bees, and 1 through 5 Neutronium Bees.

**Comment by Contrex114** [comment]
I tried using the exact recipe items (with the same NBT tags, using JEI to give the items), but it still didn't work

**Comment by cokeacolaking** [comment]
![apiary is idling](https://github.com/AllTheMods/ATM-9/assets/55969935/66b10bec-35ed-4d61-b1f6-bc17e665ed38)
![starry bee has upgrades](https://github.com/AllTheMods/ATM-9/assets/55969935/3f22407b-7a87-4474-888c-9e13d2e2870e)

**Comment by loving2** [comment]
Unfortunately it is sporadic whether or not the Apiary will work. This is due to how items with partial NBT matches are handled as inputs for recipes. It has been fixed in GTCEu-Modern's dev environment but there has not yet been a release with that fix. Once available, we will include it in an update which should make the Apiary work consistently.

https://github.com/GregTechCEu/GregTech-Modern/pull/1121

**Comment by Tamerlan-K** [comment]
Also outputs "Comb Block" instead of the corresponsding resource Comb Block, any way to fix that?

**Comment by loving2** [comment]
This has been fixed on latest ATM9 v0.3.5

**Comment by loving2** [comment]
The bee in JEI is stripped of almost all of its NBT except the ones the Apiary checks for. I do not know what happens when trying to release and recapture a bee cheated in from the JEI recipe, but I do not think that is a usual scenario. 

For testing I usually give myself one of the bee spawn eggs, use commands to give myself the 3 genes, make the gene honey treat, spawn the bee, feed the bee, capture the bee, and then test with that bee.

The commands for the genes are as follows:
`/give @s productivebees:gene{productivebees_gene_purity: 100, productivebees_gene_attribute: "productivity", productivebees_gene_value: 3}`
`/give @s productivebees:gene{productivebees_gene_purity: 100, productivebees_gene_attribute: "weather_tolerance", productivebees_gene_value: 2}`
`/give @s productivebees:gene{productivebees_gene_purity: 100, productivebees_gene_attribute: "behavior", productivebees_gene_value: 2}`

The name requirement is no longer present as of ATM9 v1.0.3 as well, which affects how the JEI recipes look. 

It is worth noting that sturdy bee cages do not work in the Apiary.

I have not been able to recreate either of the issues mentioned here on ATM9 v1.0.3
