### ISSUE TITLE
[Bug]: GregTech Mega Fusion Reactor does not work after update

### ISSUE THREAD

**Issue by SethaWetha** [AllTheMods/ATM-9#1734]
### Possible Fixes

Yes

### Modpack Version

0.2.59

### What happened?

After updating to 0.2.59, my Mega Fusion Reactor does not work at all. I assumed this was a problem with the PCH but even without the hatch the machine doesn't work so I'm opening a new issue.
When putting the resources for any recipe in, the machine shows it's working, but it's stuck at 1/4t, doesn't show power use (but the hatch looks like it's consuming energy), and does not produce anything. Image below
![image](https://github.com/AllTheMods/ATM-9/assets/45372592/d9d02b67-4424-417f-a922-b53226245534)

### latest.log

https://gist.github.com/SethaWetha/bf52b1352fbb65d8da39f9d37f504a70

**Comment by ffbw4hwj** [comment]
same here, worked for some recipes, helium plasma i think but is now stuck for star matter plasma like the one in the ss

**Comment by finshope** [comment]
With two UHV energy hatch, you can run all recipes which start heat is less or equal than 160MEU.  It seems that mega fusion reactor use same logic as ordinal fusion reactors.

**Comment by MAKtheMortal** [comment]
I've run into this, and it may be a lack of documentation. JEI doesn't say anything about heat, but it *seems* like heat is a requirement for some recipes, and as far as I've been able to figure out the only way to generate heat is to run the thing. Some recipes generate more heat than others, and require different amounts of heat as well. I've been able to bootstrap my way to crafting Star Matter Plasma with the following sequence:

Europium
Radon
Nitrogen Plasma
Iron Plasma
Naquadria
Nickel Plasma
Star Matter Plasma

There are a few problems, some of which feel like bugs:

1. If you try a recipe and don't have enough heat, the machine becomes completely hung (stuck at 1 tick) and the only way to get it working again is to break it and reform it -- which voids whatever ingredients it was trying to process, and restarts you at zero heat. Seems to me it shouldn't start at all if the requirements are not met.
2. Sometimes it hangs even though I thought I did everything right. That makes the whole heat thing feel more buggy than intentional, but I may be missing something...
3. Heat is lost over time while the machine isn't running. This may be realistic and adding to the challenge or whatever, but it's hell for automation. It either forces you to build in the above bootstrapping sequence to your autocrafting setup, or manually make sure the machine is ready before making any crafting request, running additional pre-crafting steps as necessary.

**Comment by guimas** [comment]
> I've run into this, and it may be a lack of documentation. JEI doesn't say anything about heat, but it _seems_ like heat is a requirement for some recipes, and as far as I've been able to figure out the only way to generate heat is to run the thing. Some recipes generate more heat than others, and require different amounts of heat as well. I've been able to bootstrap my way to crafting Star Matter Plasma with the following sequence:
> 
> Europium Radon Nitrogen Plasma Iron Plasma Naquadria Nickel Plasma Star Matter Plasma
> 
> There are a few problems, some of which feel like bugs:
> 
>     1. If you try a recipe and don't have enough heat, the machine becomes completely hung (stuck at 1 tick) and the only way to get it working again is to break it and reform it -- which voids whatever ingredients it was trying to process, and restarts you at zero heat. Seems to me it shouldn't start at all if the requirements are not met.
> 
>     2. Sometimes it hangs even though I thought I did everything right. That makes the whole heat thing feel more buggy than intentional, but I may be missing something...
> 
>     3. Heat is lost over time while the machine isn't running. This may be realistic and adding to the challenge or whatever, but it's hell for automation. It either forces you to build in the above bootstrapping sequence to your autocrafting setup, or manually make sure the machine is ready before making any crafting request, running additional pre-crafting steps as necessary.

I can't even get Europium to cook in the reactor. The only recipes that worked for me are Oxygen Plasma and Helium Plasma. All the others get stuck.

**Comment by MAKtheMortal** [comment]
You know what this mod needs, more UI indicators for the reasons the machine isn't working... It already has "Invalid structure" and "Fix the following issues..." (though the side button form factor on that one is easy to miss). They should add "Insufficient energy" and "Insufficient heat" when the progress stalls or runs backwards, "Invalid inputs" when there are items or fluids in the input busses/hatches but don't make up any known recipe, "Insufficient output space" when the output busses/hatches can't hold a single set of results, "Recipe too advanced for energy tier" when you need better energy hatches, "Recipe too advanced for given parallelism" when the parallel control hatch is set too high (though I still think that one should just run at a lower parallelism instead of refusing to operate), and so on. It's so frustrating when you build that big complex multiblock only to have it do nothing and you have to wonder what (of N possibilities) you're doing wrong.

**Comment by Pumpkin7266** [comment]
@Mitchell5200 I think this one is fixed, at least i have had no problems since latest update related to this

**Comment by shirousagi11** [comment]
ran into this on 1.1.0, with a 16A uv energy hatch when trying to make liquid neutronium, adding a second energy hatch seems to have fixed this but sometimes it still stops processing for a few seconds
