### ISSUE TITLE
[0.0.46] RFToolsBase Tablet with RFToolsStorage Storage Control Screen Module not opening on RMB

### ISSUE THREAD

**Issue by prdx2000** [AllTheMods/ATM-9#189]
To Recreate:

1. Place Storage Scanner
2. Link Storage Control Screen Module with Storage Scanner
3. Place Storage Control Screen Module in Tablet
4. Equip Tablet and attempt to open

**Comment by ProjectGSX** [comment]
My Storage Scanner Tablet has also stopped working since the current update was installed.

**Comment by Spunkybluepuppy** [comment]
Mine as well, it stopped working in 0.0.46 but was working fine in 0.0.45

**Comment by imposiblaa** [comment]
I am having the same issue.

**Comment by FHoulbreque** [comment]
This is still an issue. Furthermore, the module disappear if you switch the active model.

**Comment by Frostthejack** [comment]
This issue seems to extend to to the screen link module as well. it just wont open. Also the screen controller does not show how many screens are attached as it should and the book with information is broken and has broken links in it as well and hitting the help GUI button in the rftools machines does nothing. These issues don't persist when running only this mod and nothing else.

**Comment by prdx2000** [comment]
This has been an issue for 7 months. I doubt this will be fixed anytime soon honestly.

**Comment by Volzap** [comment]
Just came across this problem, I too am experiencing the issue. Would be cool if anyone took it's time to look at it

**Comment by djnifos** [comment]
We've had the fix in the pack for over a month at this point.  It should be resolved by RFTools Storage version 1.20-5.0.2 which released in January.  If this is still an issue, please update us.

**Comment by prdx2000** [comment]
Just tested this and I can confirm the issue has been resolved. Thank you very much!
