### ISSUE TITLE
[Crash]:i cant  join my single word ; 1.20.1

### ISSUE THREAD

**Issue by fahd412543** [AllTheMods/ATM-9#1915]
### Possible Fixes

Yes

### Modpack Version

0.2.61

### What happened?

I can't join my single-word for some reason I was adding a mod call (essential mod) to play with my friend and we played for 3 days but when I joined the word couldn't join, and the game crashed and I tried to delete the (essential mod) and still didn't work

### Crash Log

i dont know the log is 

### Latest.Log

the same :)

**Comment by Jmpp2909** [comment]
In order to better assist  you, your logs would be greatly appreciated!
How do I submit my log? (Client)
Go to your modpack's folder (You should be able to find an Open Folder button in your launcher)
Go to crash-reports (If there isn't a crash report, upload hs_err_pid.log or logs/latest.log)
Upload your latest crash report to https://mclo.gs/ (This will help us understand it, and remove personal info.)
Copy the link to the report and paste it here.
