### ISSUE TITLE
Skyblock edition

### ISSUE THREAD

**Issue by Joly0** [AllTheMods/ATM-9#204]
Would be great to have a skyblock edition of this modpack (also for future version of this modpack). I saw atm6 and atm7 had a skyblock edition, but atm8 didnt, sadly

**Comment by Mitchell5200** [comment]
ATM 8 has VolcanoBlock, the lava variant of skyblock

**Comment by aAndrew3030** [comment]
VolcanoBlock is a skyblock, and can relatively easily be tweaked to play it as a traditional skyblock if you really wanted to (but dont expect a tutorial)

**Comment by Joly0** [comment]
Volcano block is not a traditional skyblock, but whatever, this was not my initial request, just a subtle difference in opinion between you and me apparently.
I wont argue about if it is skyblock or not, i am requesting a skyblock edition for atm9 and am asking if its possible, to release future versions of atm as skyblock editions with the normal atm release and not like 6-12 months later, when its already time for a new minecraft version and a new atm version

**Comment by aphroidite** [comment]
To be fair, 1.18, 1.19 and 1.20 are "exploration" related versions. I like skyblock pack but I can't really see the difference between a modpack using any of these 3 versions unless items from the ancient cities are added as loot or they make the suspicious sands work when not naturally generated. Unless using kubeJS to add a custom recipe for the sculk catalyst, theres no way to obtain sculk and sensors, nor there is a way to naturally spawn a warden. Having any of these blocks wouldn't add anything to an skyblock experience to be honest, unless you are a collector and want to have every single mob, or you want a sniffer to get the torchflowers. Cherry blossoms won't spawn naturally either unless there's an island themed mod that spawns them randomly and one luckily happens to be on that specific biome, but havent seen any since 1.12.2.
1.16.5 and 1.18 did major changes related to ore generation, mob spawning, nether blocks, they added so much stuff that it was natural to make them into skyblock mode later.

**Comment by Joly0** [comment]
You are totally right, but its not only about the new minecraft version. Its also the new mods and features added to existing ones, that make new updates very interesting to play

And i can assume there are probably some people, who just cant play normal atm because modded minecraft performance is horrible, thats another reason a skyblock edition is needed, so thosw people can enjoy playing the newest iteration of atm with the new mods, the new features and such things
