### ISSUE TITLE
[Quests issues]: GregTech observer multiblock quests

### ISSUE THREAD

**Issue by frsfdc** [AllTheMods/ATM-9#2064]
### Modpack Version

0.3.2

### Describe the issue

Trying to complete the cleanroom and distillation tower quests,but the observe multiblock part won't complete.I placed it using the GT terminal too,yet it won't work,seems the observe multiblock quests are broken in latest version.
Extra: when trying to place an iron bee egg in electrolyzer,progress bar for chromite bee egg appears,yet it doesn't use it,just keeps going down to zero and back again.

**Comment by OfflineOnline** [comment]
Same here, same with the Mekanism Observe Quests.

Think it's due to the Network event handler in observeMekanism.js and observeGT.js
There's a commented-out section for handling the 'customTask' network event. When uncommented, this would likely interact with a quest system (FTBQuests) to mark tasks as completed. 

@thevortex do you know why it is like that? :)
