### ISSUE TITLE
[Bug]: SOPHISTICATED BACKPACKS BUTTON GRAPHICAL ERROR 

### ISSUE THREAD

**Issue by Ferm246** [AllTheMods/ATM-9#2141]
### Possible Fixes

Yes

### Modpack Version

ATM9 

### What happened?

Bug Report
Title: Tooltip Overlap Issue with Insert/Extract Buttons

Description:
When using the Sophisticated Backpacks mod, the tooltips for the Insert and Extract buttons overlap with other UI elements or text. This makes it difficult to read or understand the tooltips properly.

Steps to Reproduce:

Open the Sophisticated Backpacks inventory.
Hover over the Insert or Extract buttons.
Observe the tooltip's behavior and overlap with other UI components.
Expected Behavior:
The tooltips for the Insert and Extract buttons should display clearly without overlapping with other UI elements.

Observed Behavior:
The tooltips overlap with adjacent UI components, making them hard to read.

Environment Information:

Mod Version: 3.20.12
Minecraft Version:1.20.1

Additional Context:
This issue persists across different resolutions and UI scales. ALSO PERSIST WHILE ON A CLEAN INSTALL OF THE MODPACK

![2024-11-17_22 21 49](https://github.com/user-attachments/assets/0e1f9c56-3afe-4400-95c0-d747e6fa054f)

**Comment by P3pp3rF1y** [comment]
So this is caused by the fact that Quark buttons are shown over new sophisticated buttons. I would recommend disabling Quark buttons because Quark doesn't have any idea of some sophisticated features which can in the better case lead to items being put into slots where they shouldn't go (like memorized slot suddenly getting item it's not set to) but in the worse case can lead to item loss (like I am pretty sure transferring out of / into slot that has more than a max stack size will result in item loss)

**Comment by Ferm246** [comment]
thanks for the fast response friend.

**Comment by FilGoodInc** [comment]
Not sure why it was done. But Quark buttons were manually added by this PR: #2060
Reverting/removing that line in config/quark-common.toml fixed it for me and the Quark buttons remain on vanilla chests.
