### ISSUE TITLE
you can't input hoes into the harvester pylon with pipez

### ISSUE THREAD

**Issue by DisaPanda** [AllTheMods/ATM-9#235]
I haven't tried any other item transportation pipes

**Comment by neotaoisttechnopagan** [comment]
Confirmed is also an issue on v 2.32 and will be updating server later in the morning (2:30 AM currently). I have also tried LaserIO and cannot import to any side of the harvester pylon. Will attempt to use Modular Routers, Integrated Dynamics, and Mekanism as well.

**Comment by neotaoisttechnopagan** [comment]
Confirmed that cannot input into the harvester pylon using Pipez, LaserIO, Modular Routers, Integrated Dynamics, or Mekanism. 

This is due to the pylons-server.toml having the value of 'false' for "harvesterCanBeAutomated". 
I will be changing this value to true for my personal server. I do recall it was set to true by default for ATM8, because I attempted to use my same exact setup.
 
@DisaPanda, you may want to look into editing your world/serverconfig/pylons-server.toml file.

_**This appears to not be a bug, but a configuration issue and should be closed.**_
