### ISSUE TITLE
Error message when sorting inventories: Unequal before and after item counts

### ISSUE THREAD

**Issue by bagofsquirrels** [AllTheMods/ATM-9#268]
I've been getting the following error message when sorting certain inventories:

java.lang.IllegalStateException: Unequal before and after item counts

This seems fairly minor and doesn't seem to break anything. Hasn't resulted in any crashes so far.

After some experimenting, it seems the issue is caused when multiple Apotheosis Gems are in the inventory being sorted.

**Comment by petriczech** [comment]
Its happend if in chest is Flawless Lightning Gem from Apotheosis

**Comment by Acetyld** [comment]
Same here, I didn't notice it happening specifically on gems, but it happens for me as well.

**Comment by KurigohanSoreir** [comment]
The issue apparently happens with Apotheosis' Gems and Coral Tombstone's Scrolls.
It may be because these are unstackable items.

Some people also reported this issue to the [Inventory Profiles mod Git](https://github.com/blackd/Inventory-Profiles/issues/356) where some logs can be found but no solution yet.
