### ISSUE TITLE
[9-0.0.63] Productive Bees hives break Minecolonies lumberjack

### ISSUE THREAD

**Issue by NoMoreStars** [AllTheMods/ATM-9#334]
Title. When attempting to cut down trees grown in the world or naturally generating with a log beehive from Productive Bees mod, the Lumberjack stops cutting down the tree and places down a sapling, behaving as if it had finished cutting down the tree.

**Comment by superzero10** [comment]
**Current Behavior**
When attempting to cut down trees grown in the world or naturally generating with a log bee nest from the Productive Bees mod, the Lumberjack stops cutting down the tree and places down a sapling, behaving as if it had finished cutting down the tree.

**Expected Behavior**
Lumberjack should cut down the whole tree, the nest included, before placing down a sapling and moving on to the next tree.

**Reproduction Steps**
Install Productive Bees mod as well as it's dependencies
Grow saplings in the world, some generating with Bee Nests
Assign a zone to the Lumberjack


Really could need some help here
