### ISSUE TITLE
[0.56] Vial of Arcane Extraction not working

### ISSUE THREAD

**Issue by Sodfort** [AllTheMods/ATM-9#355]
I was working on upgrading my armor in a 0.56 version server I have with some friends and wanted to remove the gems from my old armor. 

I put the armor in a smithing table with the Vial of Arcane Extraction but it didn't do anything. 
Do I need to add something in the template slot or is this feature just not working as intended?

![image](https://github.com/AllTheMods/ATM-9/assets/143882983/05829b41-810a-4a32-9137-b3af6f8d47c8)

**Comment by Sodfort** [comment]
Just tested this out to make sure it's not fixed in newer versions, and the bug still persists in 0.65 which is the latest version at time of writing.

**Comment by DraxGraphics** [comment]
Still not working.

**Comment by Adrriii** [comment]
This seems to have been fixed in Apotheosis 7.0.10 and also in a patched version of 7.0.5, which is currently used in ATM9. Quick update ?

Apotheosis issue : https://github.com/Shadows-of-Fire/Apotheosis/issues/1016
patched 7.0.5 version : https://github.com/VenomCodeDev/Apotheosis/releases/tag/7.0.5.1

**Comment by Adrriii** [comment]
Fixed with 0.2.23 updating Apotheosis to 7.0.10 :) This can be closed
