### ISSUE TITLE
Insanite Block Unable to make

### ISSUE THREAD

**Issue by kimierr** [AllTheMods/ATM-9#437]
Fluidizer Casin and subsequent syntheses cannot be made, because there is only one recipe and it is yellow uranium ingots, which cannot be used in synthesis and Rossinite cannot be obtained.

**Comment by beejayceejay** [comment]
This has been broken with updates as it was once fixed, hoping for some info on how to pipe Rossinite, the output port does not want to work with any pipe since there are 2 different types of Rossinite (fluid and reactant). The recipe to get Inanite is broken due to the wrong Rossinite being created by default in atm9 as of january of 2024.
