### ISSUE TITLE
Uraninite Smelting Conflicts with GregTech

### ISSUE THREAD

**Issue by MindOfNasser** [AllTheMods/ATM-9#485]
When i try to smelt raw uraninite it make The GregTech one when i choose to change to Powah one it won't change and keep Smelting to the GregTech one, hope my explanation is clear because of my grammar :(.

**Comment by Neroland** [comment]
Yeah, this one is an annoying one... :(

**Comment by Mitchell5200** [comment]
should be fixed in v 0.1.10

**Comment by Schrimpes** [comment]
all recipe conflicts with Gregtech are annoying for me. You have to be extremely careful when crafting. especially when polymorph isn't supported, like with sophisticatet's crafting upgrades. I also have the feeling that the pack has more problems since Gregtech was included and I think this mod could be removed.

**Comment by MindOfNasser** [comment]
> should be fixed in v 0.1.10

Thanks, its fixed.
