### ISSUE TITLE
Ethylene production prevented by deactivation

### ISSUE THREAD

**Issue by ZeroReaktion** [AllTheMods/ATM-9#527]
I think it's a bad idea to disable ethylene. Why disable this? So I don't see any point in it.
I'm in favor of adding this back into ATM9, in ATM8 it hasn't been deactivated either, so why in ATM9?

**Comment by halley1989** [comment]
Was this disabled in 9.11?

**Comment by iQSJoker** [comment]
There were several bug reports about this already, it is by design. See #518 & #511.

**Comment by Cyyyro** [comment]
Mekanism Ethylene is disabled to make other players remember what playing the game is actually like.
Too many players just autopilot and build the exact same design for everything and just build what "the best" setup is and that isn't as fun as having to actually design your own power setup. Because of this, Ethylene got disabled and removed from the GBG, as well as for balancing reasons.

If you want to continue using your melons for power, consider the Culinary Generator.

**Comment by Schrimpes** [comment]
If you want to stay with Meka, there is also the bio-generator. It will take a few hundred to reach the output of the GBG (1 bio-gen = 140 fe/t) but it is possible. ^^

**Comment by alfredggttv** [comment]
Currently, Power Generation is being reworked. There should be an update in the near future that will bring Ethylene back, but at a much lower generation rate. Tons of other generators will also be buffed, so make sure to check that out.
