### ISSUE TITLE
[0.1.12] Create's Crushing Wheel Recipe Bug

### ISSUE THREAD

**Issue by AverageOtter** [AllTheMods/ATM-9#539]
Create Crushing wheels have 7 recipes for processing Iron Ore into both Raw Iron Ore and Crushed Raw Iron Ore.
Some of which are more favorable with most being a 1:1 ratio and others as high as a 1:3 ratio with 75% for a 4th.
I suspect this is the case for all the ore processing recipes. 
![image](https://github.com/AllTheMods/ATM-9/assets/57277126/fdeb0f50-feb9-4cc0-a91c-de6ca639366b)

**Comment by deggy42** [comment]
Seconding this with a little more detail - Crushing Wheels appear to be intended to give more favorable output for deeper-generated ores. There's a recipe that gives cobblestone and iron, but the recipe that gives cobbled deepslate gives more iron. The ore input for the recipes has been set up with forge tags instead of specific items, so any ore can randomly process into 1-4 crushed and any kind of cobblestone.

The solution is to change the recipes so that they require the specific kind of ore, not just any ore of the appropriate material.
