### ISSUE TITLE
Create recipe to pattern grid crash

### ISSUE THREAD

**Issue by petriczech** [AllTheMods/ATM-9#568]
If click to add recipe (Electric Motor) to Pattern Grid (Refined Storage), game "crash" like screen. I play single player.

![image](https://github.com/AllTheMods/ATM-9/assets/5469703/d98a327f-44da-4686-8763-699bb67661de)

**Comment by screret** [comment]
...& the log?

**Comment by petriczech** [comment]
[log.log](https://github.com/AllTheMods/ATM-9/files/12861025/log.log)

**Comment by Ciznia** [comment]
Electric motor have a special pattern shape that cause RS to crash you like this you need to put it yourself item by item and this will work but don't shift + click on the interogation button from JEI

Because
A normal craft is like

[0, 1, 2
 3, 4, 5
 6, 7, 8]
 And it's that in the pattern manager but they can have more line
 And the button try to do 
[  

            7
          ]
