### ISSUE TITLE
Crashed and not even work

### ISSUE THREAD

**Issue by CEKPET1** [AllTheMods/ATM-9#621]
Good Day, everyone, not so long ago (10/15/23) I encountered a problem: during the game the server crashed and gave the following error (Picture). I tried a couple of tips from the internet, but they didn't work. Maybe someone can help with advice?
![Снимок экрана 2023-10-16 101101](https://github.com/AllTheMods/ATM-9/assets/148038141/6f8b3528-4a42-4475-b26c-edda181088d6)

**Comment by Holysweet** [comment]
java.lang.indexoutofboundsexception:readerindex(63)+length(1)exceeds writerindex(62):Pooledunsafedirectbytebuf(ridx:62,widx62,cap:62 and other variants like it seem to be cause by maps (treasure maps, normal filled maps, twilight forest map) in either the players inventory or on the wall in someones base when updateing. 

The work around is either to use a world editor to remove the map from the players inventory or base (itemframe) and then everything seems to work fine again. If this is to complicated you could delete the player file from the server to wipe the entire inventory but this fully resets the player so is undesirable.

I have no idea what is causeing this because it also happens with normal minecraft maps hope the ATM team is way smarter then me because I was unable to figure it out further then this.

**Comment by CEKPET1** [comment]
> java.lang.indexoutofboundsexception:readerindex(63)+length(1)exceeds writerindex(62):Pooledunsafedirectbytebuf(ridx:62,widx62,cap:62 and other variants like it seem to be cause by maps (treasure maps, normal filled maps, twilight forest map) in either the players inventory or on the wall in someones base when updateing.
> 
> The work around is either to use a world editor to remove the map from the players inventory or base (itemframe) and then everything seems to work fine again. If this is to complicated you could delete the player file from the server to wipe the entire inventory but this fully resets the player so is undesirable.
> 
> I have no idea what is causeing this because it also happens with normal minecraft maps hope the ATM team is way smarter then me because I was unable to figure it out further then this.

Thank you for your advice. World editor don't work on this version, so as I said, I try methode to delete player file (anyway I playing singleplayer), but for some reason files appeare again, so as an error.

**Comment by CEKPET1** [comment]
So I found the solution and good World Editor, so all problem with TF maze map, so I don't know, is that my problem, or modpack, but problem is a problem.
