### ISSUE TITLE
Tin & GregTech

### ISSUE THREAD

**Issue by Ashsilvara** [AllTheMods/ATM-9#752]
AllTheOres Tin is not OreDictionary for GregTech attempting to use in Extruder for Tin Rings.

**Comment by zookeper** [comment]
Yeah a fair amount of gregtech is broken due to greg using his own ore labels rather than minecrafts.

**Comment by screret** [comment]
tf
we use all the same tags as everyone else
except for aluminium.

**Comment by Graphicscore** [comment]
> tf we use all the same tags as everyone else except for aluminium.

I think the issue is not the ores having the wrong tag, it's the gregtech machine explicitly expecting the ores with the gtceu tag, which is not added to the ores

**Comment by Graphicscore** [comment]
@screret 

Is it possible that the recipes in gregtech are registered with the "wrong" tag? I am not really experienced in mod dev. It seems like it is registering the recipes under the forge:ores/stone/xy pattern (because it will use the first tag found), which the vanilla/ATM ore blocks seem to not be having. (See screenshots)

![javaw_lUFMIXTeXO](https://github.com/AllTheMods/ATM-9/assets/5658012/1725a645-da41-404e-b67f-b9c4f581800c)
![zxN1AlP4mh](https://github.com/AllTheMods/ATM-9/assets/5658012/1a5b1981-e7ff-4e24-a31a-cce462f357bd)

**Comment by screret** [comment]
hmmm
we kind of need to do the `forge:ores/stone/thing` thing though, because some stone types have different outputs for example.

**Comment by Graphicscore** [comment]
> hmmm we kind of need to do the `forge:ores/stone/thing` thing though, because some stone types have different outputs for example.

Can we not just register all tags found? The second tag in the tags array is the "correct" one in this case for example

**Comment by screret** [comment]
well no
because then netherite ores would macerate into stone dust with stone ore output chances.

**Comment by Graphicscore** [comment]
> well no because then nether ores would macerate into stone dust with stone ore output chances.

Other alternative would maybe to give the vanilla ores the corresponding ores tags for gregtech.

Like vanilla  gold ore and nether gold ore are both not working in the forge hammer. It's supposed to accept the gregtech gold ores, which dont seem to exist in the overworld in ATM9

**Comment by zookeper** [comment]
It's impossible to progress in a world that you can't just regenerate, It's not just tin, it's all of the ores that minecraft already has should just go into gregtech machines but they aren't. So we can assume that the gregtech tags are incorrect as if they were correct the ores would produce.

**Comment by zookeper** [comment]
Server host couldn't even spawn emerald ore with the tag gregtech, it just forced spawned as minecraft ore. so i think something with the allores dictionary is broken as he had to manually spawned crushed emerald ore so I could sift it into a flawless jewel.

even then, minecraft emerald ore should still macerate in gregtech macerator.

**Comment by zookeper** [comment]
I would like to note that kubejs is conflicting with some gregtech ores.

**Comment by Graphicscore** [comment]
> I would like to note that kubejs is conflicting with some gregtech ores.

In what way? I opened a pull request yester which adds the tags that gregtech expects to the vanilla and alltheores ores via kubejs, but I am not sure if this is the preferred way of doing it. It works though 😄

**Comment by loving2** [comment]
What version are you on? I just tested on 0.2.14, 0.2.15, and 0.2.18b and could not reproduce the Alltheores tin ingot to gtceu tin ring issue.

As for the issue with getting flawless emeralds, you need to look in the Nether for GT's emerald ore as that allows for the processing.  
![image](https://github.com/AllTheMods/ATM-9/assets/26778483/ab38998d-e7e1-44e5-97a5-be4c6b58ac52)
![image](https://github.com/AllTheMods/ATM-9/assets/26778483/431a43c3-3497-44b2-acb7-4a38bbdb5f97)

**Comment by loving2** [comment]
Ah okay I think I understand the emerald issue, is it that regular silk-touched emerald ore doesn't work in a macerator/forge hammer? I'll double check, but yeah I think that PR would fix that

**Comment by zookeper** [comment]
Right but on this server where the nether was generated before the gtech stuff had the chance to we can't find any of the ores that gtech expects us too and this makes it incredibly difficult to find anything please make all the gtech ores spawn in the allthemodium dimension, thanks.

**Comment by zookeper** [comment]
loving2. 

The issue is that the ores needed to make lenses without having to use dye don't work. I was forced to make dye, in a world like ours where stuff wasn't generated, it took me two whole days to find realgar.... 

The issue isn't so much so that the ores aren't spawning, who cares about gregtech ores?? we already have ores.... they just wont go into gregs machines cause he is a maniac.

**Comment by loving2** [comment]
All the GT ores *should* spawn in the mining dimension, but that only happened after one of the updates so I can definitely see how some worlds/servers wouldn't have it easily accessible without regenerating the dimension.

The latest update (0.2.19) should now allow minecraft emerald ore into the GT Macerator to get crushed emerald, which can then be purified in an Ore Washer, which can then go into the Sifter and get the flawless jewel. It should also cover the other silk-touched ores, but do let me know if this continues being an issue!

**Comment by zookeper** [comment]
Yes I honestly flew for a few hours trying to find those ores needed to progress in GT.

it macerates like a charm, thank you so much! if I find any other issues with the ores or macerator, ill try and post it here

**Comment by zookeper** [comment]
if the ores are generating in the nether part of the atm mining dimension, i was getting zero nether silk touched emerald ore with my digital miner, maybe the issue was with atm mining dim. The nether was generated quite early in the pack, same with atm dim, I just couldn't find emerald nether ore in either nether or atm dim at all. I assume the gtech emerald ore was supposed to spawn in both of those dims.

**Comment by zookeper** [comment]
and i would be fine with only finding a tiny bit of the emerald gtech ore in the nether part of the atm dim but that was not happening. tbh you can't actually progress without that jewel, its used to make the first part to the cutter itself.

So i really appreciate the change even though the questline states otherwise.
