### ISSUE TITLE
[Suggestion] Make a recipe for intricate hellforged parts

### ISSUE THREAD

**Issue by ryennce** [AllTheMods/ATM-9#763]
- It's a component for the ATM star and honestly... Dungeon delving for hours and hours would only get you like 5/6 it's such a boring task. 
- you need 4 to make a star, meaning you need 76 of those to get 19 stars (for the block/bee) 

Having a recipe would be good. Something with netherite and hellforge ingots I guess

**Comment by Ahbeaver** [comment]
I agree with this completely. I spent 4-5 hours unlocking the Blood Magic mines (admitedly this was partly from my own stupidity) and afterwards it took me a hour to find one intricate hellforged parts. Considering how many stars you need for the bee and how many intricate hellforged parts you need per star we definatly need some alternate recipe for intricate hellforged parts. My suggestion is to add a recipie similar to armor trim duplication but instead of diamonds on the outside surround it with etherial slates.

**Comment by jespencer** [comment]
Please change the drop rate or add recipe, drop rate is way to low.  Example from last night.
 20 miner keys, open 20 rooms, avg 3 chest per room = 1 hellforge part.  
 
 I'm assuming most people are trying to get to the bee, so that is 18 Stars which require 72 hellforge parts.  At one part per 20ish keys, you are looking at 1440 keys.  Compared to the other sub components of the Star it is way out of wack time wise(and it is rng based).

**Comment by BrettMoan** [comment]
ditto on this. the issue is that the IHP. `Intricate Hellforged Parts` is needed for the `Reinforced Speed Rune` 4 of which are are needed for each `Wither's Compass`. 

As-is the `IHP` is an random drop only found in the lootr chests and a rare rate. Almost all other components of the ATM star are able to be automated or at least non-rng repeated (like automate ingredients for summoning a boss fights), 

`IHP` is _not farmable_, and as such the entire ability of creating 18 atm Stars comes down to being able to find not a handful of RNG drops but 72 copies of one specific drop that requires opening many many lootr chests in the dungeons.

That said, I do like being made to go deeper into Blood magic and go to this dimension, but i think there should be added a route to automate this via further blood magic progression. 

while i've never done it, to my understanding Blood magics `Will Crystals` _are_ a end-of-mod farmable item, and so if you made a recipe for `2 IHP` that required the with will crystals and required an initial copy of the `IHP` (similar to smithing templates) I think it will keep the point of automation + mod progression.

I'm going to try and make a custom recipe for a server I help admin on, once i have the recipe, i'll raise a PR in case you like the approach.
