### ISSUE TITLE
[ATM 9 - v0.2.22] Elevator Mod Elevator Requires Standard Ender Pearls

### ISSUE THREAD

**Issue by TrueRocket** [AllTheMods/ATM-9#869]
The elevator blocks from the Elevator Mod specifically require normal ender pearls although most other recipes in the pack that use ender pearls accept any variation of them from Enderman Overhaul.

Elevator recipe:

![image](https://github.com/AllTheMods/ATM-9/assets/72956322/25156a1f-8632-4f40-a955-9beaae57ed20)
![image](https://github.com/AllTheMods/ATM-9/assets/72956322/7ac95d3c-624f-4d91-a584-ff558eeb611f)

Attempt to craft the recipe with an ender pearl variant (specifically the warped pearl):

![image](https://github.com/AllTheMods/ATM-9/assets/72956322/47686cc0-193d-4f89-845b-0d8cb5d54385)

Other recipe that uses ender pearls:

![image](https://github.com/AllTheMods/ATM-9/assets/72956322/0b5ced62-98c0-4d6e-8954-a6fe82900235)
![image](https://github.com/AllTheMods/ATM-9/assets/72956322/5ca6d0c5-bd40-473d-ab7d-085bf4dd208e)

I also noticed that a couple other recipes, including the dimensional walls from DimStorage and the teleport rail from UsefulRailroads, also have this issue.

EDIT: Vanilla recipes, including eyes of ender, also have this issue.

**Comment by MikeyM3thodic4l** [comment]
So to clarify here, the overhaul pearls have the forge:ender_pearls tag so they work in any recipies that look for that (including the last recipe screenshot in OP, if that doesn't work then there's something else going on too) instead of just the minecraft:ender_pearl. I think that the fix is simply using KubeJS to unify all the recipies to looking for the tag instead of the item. Temporary fix in the meantime if you are in single player or on your own server is to datapack in a recipe that turns any forge:ender_pearls into a minecraft:ender_pearl
