### ISSUE TITLE
 ATM9-0.2.28 Generators Galore - Specific generators do not work

### ISSUE THREAD

**Issue by FeenieTheFeenus** [AllTheMods/ATM-9#966]
The Netherstar, Ender and Halitosis generaotrs does not accept coal or charcoal but the other pictured generators do, despite them saying they accept solid fuel. 
![oKj19rc](https://github.com/AllTheMods/ATM-9/assets/153351104/0319b430-4c33-4110-865d-49be9b5438f2)

Side note: The generators have small seems that you can see through: 
![g1Tqak6](https://github.com/AllTheMods/ATM-9/assets/153351104/b396f6aa-11b9-484d-a8cf-1172c24db74f)

**Comment by DragonsKeep89** [comment]
If they are anything like what they were in older versions they have specific fuels and the others are not working correctly.  The netherstar generator burns netherstars, ender generator is supposed to burn things from the end, and halitosis is supposed to burn dragons breath.  It has been a long time since I have used them but that is what I recall.

**Comment by FeenieTheFeenus** [comment]
Had a look at the mod page and yeah, my bad. Although to be fair it does say it accepts solid fuel in it's description, so I assumed it would use the same fuels as the other generators.
